### ISSUE TITLE
NoneType' object has no attribute '_ldapinfo'

### ISSUE THREAD

**Issue by mubix** [skelsec/msldap#46]
When attempting to run a command via non-interactive mode an error occurs:

For example:
```
# msldap -n ldap+ntlm-password://testing.local\\notadmin:Password1@192.168.8.100 adinfo
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/msldap/examples/msldapclient.py", line 113, in do_adinfo
    self.adinfo = self.connection._ldapinfo
AttributeError: 'NoneType' object has no attribute '_ldapinfo'
```

What am I doing wrong here?

**Comment by skelsec** [comment]
When starting in interactive mode (not the one you showed) msldapclient automatically performs a `logon` on your behalf before giving you access to the interactive shell.  
In non-interactive mode `batch` mode this `logon` command is not getting issued because there can be commands you might wish to run which affect the `logon` process.  
Therefore, the correct way to use the non-interactive mode is to always manually issue a logon like  
`msldap -n ldap+ntlm-password://testing.local\\notadmin:Password1@192.168.8.100 logon adinfo`

**Comment by mubix** [comment]
Thanks! That works perfect :)
